/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-error-container': '#ffdad6',
        'secondary-fixed': '#e9ddff',
        'tertiary-container': '#000000',
        'on-secondary-fixed-variant': '#5516be',
        'surface-container': '#201f1f',
        'tertiary-fixed-dim': '#4cd7f6',
        secondary: '#d0bcff',
        'inverse-on-surface': '#313030',
        'surface-container-low': '#1c1b1b',
        'on-tertiary-fixed-variant': '#004e5c',
        'on-error': '#690005',
        'surface-bright': '#393939',
        'primary-fixed': '#e2e2e2',
        'on-primary': '#303030',
        'on-secondary': '#3c0091',
        'inverse-surface': '#e5e2e1',
        'secondary-fixed-dim': '#d0bcff',
        'on-surface': '#e5e2e1',
        'inverse-primary': '#5e5e5e',
        'on-primary-fixed-variant': '#474747',
        'outline-variant': '#4c4546',
        'surface-dim': '#131313',
        'on-tertiary-container': '#008197',
        'tertiary-fixed': '#acedff',
        'on-secondary-container': '#c4abff',
        tertiary: '#4cd7f6',
        'on-primary-container': '#757575',
        'secondary-container': '#571bc1',
        'surface-tint': '#c6c6c6',
        'surface-container-highest': '#353534',
        'on-surface-variant': '#cfc4c5',
        primary: '#c6c6c6',
        'surface-container-high': '#2a2a2a',
        surface: '#131313',
        error: '#ffb4ab',
        'on-tertiary-fixed': '#001f26',
        'on-background': '#e5e2e1',
        outline: '#988e90',
        'surface-variant': '#353534',
        'surface-container-lowest': '#0e0e0e',
        'on-primary-fixed': '#1b1b1b',
        'error-container': '#93000a',
        'primary-fixed-dim': '#c6c6c6',
        'on-secondary-fixed': '#23005c',
        'primary-container': '#000000',
        'on-tertiary': '#003640',
        background: '#131313',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '24px',
        unit: '8px',
        'container-max': '1440px',
        gutter: '32px',
        'margin-desktop': '80px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      fontFamily: {
        serif: ['"Instrument Serif"', 'serif'],
        sans: ['Geist', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['80px', { lineHeight: '1.0', letterSpacing: '-0.02em', fontWeight: '400' }],
        'display-lg-mobile': ['48px', { lineHeight: '1.1', fontWeight: '400' }],
        'headline-lg': ['48px', { lineHeight: '1.2', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '300' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
